version: '3'

volumes:
    data:

services:
    mariadb:
        image: mariadb
        volumes:
            - data:/var/lib/mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
    mysql:
        image: "mysql"
        volumes:
            - data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
    postgres:
        image: postgres
        volumes:
            - data:/var/lib/postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: homestead
            POSTGRES_PASSWORD: secret
    postgis:
        image: mdillon/postgis
        volumes:
            - data:/var/lib/postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: secret
    redis:
        image: redis:alpine
        volumes:
            - data:/var/lib/redis
        restart: always
        ports:
            - "6379:6379"
    memcached:
        image: memcached:alpine
        volumes:
            - data:/var/lib/memcached
        restart: always
        ports:
            - "11211:11211"
    elasticsearch:
        image: "elasticsearch:2-alpine"
        volumes:
            - data:/var/lib/elasticsearch
        restart: always
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana:
        image: kibana
        ports:
          - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        links:
          - elasticsearch
    metabase:
        image: metabase/metabase
        volumes:
            - data:/var/lib/metabase
        restart: always
        ports:
            - 3000:3000
        environment:
            JAVA_TIMEZONE: Aisa/Taipei
        links:
            - mysql
            - mariadb
            - postgres
            - postgis
    portainer:
        image: portainer/portainer
        volumes:
            - data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        ports:
            - 9527:9000

